# ===================================================================
# CONFIGURATION GENERALE
# ===================================================================
spring.application.name=TnbSwitch-Backend
server.port=8080

# Déclaration du profil actif par défaut (Sera écrasé en prod par la ligne de commande)
spring.profiles.active=dev

# Configuration de l'encodage pour éviter les soucis avec les accents des SMS
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Configuration JSON (Formatage propre des dates ISO-8601 pour l'API Rest)
spring.jackson.serialization.write-dates-as-timestamps=false